"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7hxh__s%(2^m5ccb$gx*&y!v3yvdk4^ol_q65&v+(xoby-zw3('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['zidapi.rozahsoft.com','www.zidapi.rozahsoft.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    )
}


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


X_MANAGER_TOKEN= 'eyJpdiI6Ijc5TWcvZGE0K1R3R2hQNWhFTjdybkE9PSIsInZhbHVlIjoiRUphemM2dHU5Z0djdjJreGw1bFJPVlNnQ2pSblRiWEhYQ0J3dUVnL1BjZmJNaWtBQ1pWK1hxaVE0TnhuaDZ3K3ZoTVg2OUdKVnBKb0p6ZXBFKzZCdU9lazBPMUg2RnVLZEhra1JMTVVKTDV5bkErZStuMHNiT092Z1Q4Y1QzbkUrdUd2V2Z0emFVdHJHcmRWUmJpVksxZmpDVnVUN2MycGVqa1J1a0VnMVVWamdxc1FSb1ltaWpZWnA1MzNnREFYSlJmUXhzV1BVVjlJelhyZjUyZE5iK1VEWkRZU0hTeFRmZ3l1dldWc2gwTT0iLCJtYWMiOiI0NzJlMzc4MGJlNjhkYzhlNzM0YWIxYzljNGFjNWY0ZWJhMzg1MzQ0NjcxZDNjOWVmYTRlMGM1NGFhNzI0ODE5IiwidGFnIjoiIn0='



AUTHORIZATION='Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxMTciLCJqdGkiOiI1YjZmYWFhMTA2NzFjZmU4ZDMzYTYyNWVjZDcxZmJjNTVmNGM2ZGUzY2Q4NmViZmYxNTNkODdjMmZkMWVmMTI2ODY4ZWFiMDNmYTczZDJmZiIsImlhdCI6MTYzMDg1NDIxOS4zMDUzOCwibmJmIjoxNjMwODU0MjE5LjMwNTM4MywiZXhwIjoxNjYyMzkwMjE5LjI5OTg0Nywic3ViIjoiMTQ0NTI3Iiwic2NvcGVzIjpbInRoaXJkLXBhcnRpZXMtYXBpcyJdfQ.BEr-Z8gi1O_QVxe_pZkdk9Za8kQ0Bw_F3819G7t5NcQBZ475c6f0vMPFECG4K76MFSzvBcGm53cv6DRbCGcWZE6A_r_nuRcF9R9udzh8pMzfH6fDszWZeXrAKrLlim2O_YtURxNtGgQXzKZQ6X3RSn3NP57rTJ9RvhAj8PqwMgZ8ixAQkdrqIIQVxlE4IQXOFSMjHFp1CTxOueq4dELXIS3g8vE_5wjksOT01GXoY8Wr5VulfAro7zC2dvj9KF12msqc4IrDDpPgL-LFo8bTau373vAeL825pyAnFVH9oBJgvbNLwtKm06QTxT0Jndz03feyfw5I3M68fqfPVAsCXic-5OPfuk62CS0zaX39SoN_ULbCXH7k_UGA_YXhP0Nf1oCh3I7My_RnefejVTjrVdlGtfFub0wbhHItirHeOqysBNhrdJdkyGYZi6Nw78zCA5nfnFLCDHs3PAxyvGP_LjLa3xdwnr-XWD4sb2jKjLTgN41kT1ZOlxM4E_c-kf7DZkHKLxAxQwCcJ3N6EVnmbG68TTL4vT3osewcnD0rtqvFRM5s-tC2zwzheoH5onsAX_j5X1ac79M9FG8FvwMWG878XOYI2riWWY1PGQj_7uGpILeJlIixpZWVK4ne6c_8EZsQwxpzzbtu02AcD-1y95vFvYaZZoWNrWiDeqXYgPE'